spring:
  application:
    name: spring-cloud-config-server
    
server:
  port: 8888
  
---
spring:
  cloud:
    config:
      server:
        git:
          #uri: file:///Users/gyelwand/Documents/spring-microservice-with-docker/git-localconfig-local
          uri: https://github.com/gangadharyelwande/Microservices-with-Docker-Mongo.git
          skipSslValidation: true
          username: gangadharyelwande
          password: October2018$
          
          #https://github.com/gangadharyelwande/Microservices-with-Docker-Mongo/tree/master/git-localconfig-local